apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloud-app

resources:
  - ../../base

# CI rewrites `newTag` here on every deploy. Keep this block in sync
# with image-patch.yaml.
images:
  - name: registry.digitalocean.com/adrian-cloud-app/cloud-app
    newTag: latest
